### ISSUE TITLE
A friendly message about the state of this repository

### ISSUE THREAD

**Issue by Nikronic** [boschresearch/multiplicative-filter-networks#1]
Hi,
Simply, I wanted to know if you have any plan to release the source code in the near future.

Bests
Nikan

**Comment by dwillmott** [comment]
Hello Nikan,

Thanks for your interest and sorry for the wait! We're currently in the process of clearing the code internally and will be making it public as soon as possible, my hope being before the start of the conference of Monday.

Best,
Devin

**Comment by Nikronic** [comment]
Thank you and wish you best of luck for the future works!

**Comment by Frank-Dz** [comment]
Hi Any updates regarding the remaining experimental parts?
