### ISSUE TITLE
The PSNR results fluctuate abnormally between 1000 and 2000 iters and periodically occur in subsequent iterations. .

### ISSUE THREAD

**Issue by EmiyaMitsuhid** [boschresearch/multiplicative-filter-networks#4]
Hi,
I want to ask a question that I found the psnr results fluctuate abnormally between 1000 and 2000 iters from 50 to 35 and periodically occur in subsequent iterations. Is this cyclical fluctuation consistent with your experimental results?

**Comment by kecol** [comment]
@EmiyaMitsuhid , your description sounds like something related to the use of a big learning rate value.
